trigger:
  branches:
    include:
      - main
      - restore-commit

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'

  - script: dotnet build
    displayName: 'Compilar proyecto'
